apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: webhook-receiver
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: fred-william-node-express-pipelinerun-
      spec:
        serviceAccountName: quay-bot
        params:
          - name: source-repo
            value: https://github.com/cloud-native-garage-method-cohort/fred-william-buildah-assignment.git
          - name: image-repo
            value: quay.io/fred_aklamanu_ibm/nextapp
          - name: app-name
            value: fred-william-node-express-app
        pipelineRef:
          name: fred-william-node-express-app
        workspaces:
        - name: pipeline-shared-data
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
