apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webhook-receiver
rules:
  - resources:
      - eventlisteners
      - triggerbindings
      - triggertemplates
      - triggers
    apiGroups:
      - triggers.tekton.dev
    verbs:
      - get
      - list
      - watch
  - resources:
      - pipelineruns
      - pipelineresources
    apiGroups:
      - tekton.dev
    verbs:
      - create
      - list
  - resources:
      - configmaps
    apiGroups:
      - ""
    verbs:
      - list
      - watch
      - get
