apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webhook-receiver-interceptors-view-sample-nextapp
subjects:
  - kind: ServiceAccount
    name: webhook-receiver
    namespace: sample-nextapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webhook-receiver-interceptors-view
